plugins {
    id 'nva.identity.service.java-common-conventions'
}

dependencies{
    implementation(nvaCatalog.jackson.databind)
    implementation(nvaLibs.json)
    runtimeOnly(nvaCatalog.jackson.core)
    runtimeOnly(nvaCatalog.jackson.dataformat.xml)
    runtimeOnly(nvaCatalog.jackson.datatype.jdk8)
    runtimeOnly(nvaCatalog.jackson.datatype.jsr310)
    runtimeOnly(nvaCatalog.jackson.datatype.problem)
    runtimeOnly(nvaCatalog.jackson.module.parameter.names)
}
