plugins {
    id 'nva.identity.service.java-common-conventions'
}

dependencies {
    api(nvaLibs.apigateway)
    api(project(":customer-commons"))
    api(project(":user-access-commons"))
    api(project(":user-access-public-model"))
    api(project(":user-access-service"))
    api(project(":user-creation"))
    implementation(nvaCatalog.jackson.databind)
    implementation(nvaCatalog.wiremock.core)
    implementation(nvaLibs.core)
    implementation(nvaLibs.json)
    implementation(nvaLibs.testutils)
}

test {
    environment "COGNITO_HOST", "example.com"
    environment "AWS_REGION", "eu-west-1"
    environment "API_DOMAIN", "localhost"
    environment "CUSTOMERS_TABLE_NAME", "CustomersTable"
    environment "USERS_AND_ROLES_TABLE", "UsersAndRolesTable"
}
