version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - pip3 install aws-sam-cli
  build:
    commands:
      # Force build of user-access-service to produce zip for Lambda Layer
      - ./gradlew :user-access-service:clean :user-access-service:build
      - sam build
      - sam package --s3-bucket $SAM_BUCKET --output-template-file transformed_raw.yaml
      - echo "{}" > configuration-dev.json
      - echo "{}" > configuration-prod.json
    post_build:
      commands:
        # Use timestamp to force update of ApiGatewayCreateDeploymentCustomResource
        - BUILD_TIMESTAMP=$(date '+%s')
        - envsubst '${BUILD_TIMESTAMP}' < transformed_raw.yaml > transformed.yaml
artifacts:
  files:
    - transformed.yaml
    - configuration-dev.json
    - configuration-prod.json