openapi: 3.0.0

info:
  title: institutions proxy api
  description: api description for institutions proxy
  version: 1.0.0

paths:
  /roles:
    post:
      summary: Adds new Role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'

      responses:
        '200':
          description: Successful creation of role. Returns the generated role
components:
  schemas:
    Role:
      properties:
        rolename:
          type: string