AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Stack for Cognito and users, roles and customer institution services.

#
#  After Cognito has been created it must be registered with Feide
#  The user pools service provider URN is: urn:amazon:cognito:sp:<user_pool_id>
#
#  Information needed is:
#
#    Amazon Cognito Domain:  https://nva-test.auth.eu-west-1.amazoncognito.com
#    Amazon Cognito URN:     urn:amazon:cognito:sp:eu-west-1_JRPabH2jf
#

Parameters:
  # Parameters from Cognito
  AuthenticationDomainPrefix:
    Type: String
    Default: nva-develop
    Description: The prefix for the Cognito domain that hosts the sign-up and sign-in pages for your application.
  FeideMetadataUrl:
    Type: String
    Default: https://idp-test.feide.no/simplesaml/saml2/idp/metadata.php
    Description: Link to the the identity provider details.
  FrontendApplicationUrl:
    Type: String
    Default: https://frontend.dev.nva.aws.unit.no
    Description: A base URL for the callbacks for the identity providers.
  ParameterNamePrefix:
    Type: String
    Description: Prefix used for naming parameters.
    Default: ''

  # Parameters from nva-cognito-pre-token-generation-trigger
  CustomDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Custom API to connect this lambda to
    Default: CustomDomain
  UserServiceSecretName:
    Type: String
    Description: Name of the Secret for Users and Role Service
    Default: UserCatalogueApiKey
  UserServiceSecretKey:
    Type: String
    Description: Key in the Secret for Users and Role Service
    Default: ApiKey
  MaxConcurrency:
    Type: String
    Description: Maximum capacity for provisioned concurrency
    Default: 10
  MinConcurrency:
    Type: String
    Description: Minimum capacity for provisioned concurrency
    Default: 1

Resources:

  ### Cognito ##########################################################################################################

  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UsernameAttributes: [email]
      EmailConfiguration:
        EmailSendingAccount: 'COGNITO_DEFAULT'
      MfaConfiguration: 'OFF'
      LambdaConfig:
        PreTokenGeneration: !Sub
          - ${TriggerFunctionArn}:live
          - TriggerFunctionArn: !GetAtt TriggerFunction.Arn
      Schema:
        - Name: affiliation
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: application
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: applicationRoles
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: commonName
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: feideTargetedId
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: feideId
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: identifiers
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: orgEmail
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: orgLegalName
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: orgName
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: orgNumber
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: schoolList
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: yearOfBirth
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: customerId
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: cristinId
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: accessRights
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: hostedOrgNumber
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: hostedAffiliation
          AttributeDataType: String
          Mutable: true
          Required: false

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Ref AuthenticationDomainPrefix

  UserPoolIdentityProviderFeide:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      AttributeMapping:
        custom:affiliation: eduPersonAffiliation
        custom:commonName: cn
        custom:feideId: eduPersonPrincipalName
        custom:feideTargetedId: eduPersonTargetedID
        custom:orgLegalName: eduPersonOrgDN:eduOrgLegalName
        name: displayName
        custom:orgEmail: eduPersonOrgDN:mail
        custom:orgName: eduPersonOrgDN:o
        custom:orgNumber: eduPersonOrgDN:norEduOrgNIN
        custom:schoolList: feideSchoolList
        custom:yearOfBirth: feideYearOfBirth
        given_name: givenName
        email: mail
        family_name: sn
        custom:hostedOrgNumber: eduPersonOrgUnitDN:norEduOrgUnitUniqueIdentifier
        custom:hostedAffiliation: eduPersonScopedAffiliation
      UserPoolId: !Ref UserPool
      ProviderName: FeideIdentityProvider
      ProviderType: SAML
      ProviderDetails:
        MetadataURL: !Ref FeideMetadataUrl

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      GenerateSecret: false
      SupportedIdentityProviders:
        - !Ref UserPoolIdentityProviderFeide
      UserPoolId: !Ref UserPool
      CallbackURLs:
        - !Ref FrontendApplicationUrl
      LogoutURLs:
        - !Sub '${FrontendApplicationUrl}/logout'
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - aws.cognito.signin.user.admin

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: True
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !Sub 'cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'

  # IAM role used for authenticated users
  FeideAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'cognito-identity.amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: IdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: 'CognitoAuthorizedPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'mobileanalytics:PutEvents'
                  - 'cognito-sync:*'
                  - 'cognito-identity:*'
                Resource: ['*']

  # IAM role used for unauthenticated users
  UnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'cognito-identity.amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: IdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated
      Policies:
        - PolicyName: 'CognitoUnauthenticatedRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'mobileanalytics:PutEvents'
                  - 'cognito-sync:*'
                Resource: ['*']

  # Assigns the roles to the Identity Pool
  IdentityPoolRoleMapping:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt FeideAuthenticatedRole.Arn
        unauthenticated: !GetAtt UnauthenticatedRole.Arn

  # IAM role used for users allowed to publish
  PublisherRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: 'cognito-identity.amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud':
                  Ref: IdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: PublisherPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'mobileanalytics:PutEvents'
                  - 'cognito-sync:*'
                Resource: ['*']

  FeideAuthenticatedGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: FeideAuthenticatedGroup
      Description: Common users authenticated with Feide
      RoleArn: !GetAtt FeideAuthenticatedRole.Arn
      UserPoolId: !Ref UserPool

  PublisherGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: PublisherGroup
      Description: Users allowed to publish
      RoleArn: !GetAtt PublisherRole.Arn
      UserPoolId: !Ref UserPool

  ### Cognito Trigger ##################################################################################################

  TriggerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"
        - PolicyName: AddUserToGroup
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminAddUserToGroup
                  - cognito-idp:AdminUpdateUserAttributes
                Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*'
        - PolicyName: GetSecretValue
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref UserServiceSecret

  InvokeTriggerPermission:
    DependsOn:
      - TriggerFunctionAliaslive
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TriggerFunction
      Principal: cognito-idp.amazonaws.com

  InvokeTriggerLivePermission:
    DependsOn:
      - TriggerFunctionAliaslive
      - TriggerFunction
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub '${TriggerFunction}:live'
      Principal: cognito-idp.amazonaws.com

  TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cognito-pre-token-generation
      Handler: no.unit.nva.cognito.TriggerHandler::handleRequest
      Runtime: java11
      Role: !GetAtt TriggerExecutionRole.Arn
      MemorySize: 1408
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Timeout: 10
      Environment:
        Variables:
          #TODO: Can be removed when trigger is invoking functions directly
          CUSTOMER_API_SCHEME: https
          CUSTOMER_API_HOST: !Sub 'api.${CustomDomain}'
          USER_API_SCHEME: https
          USER_API_HOST: !Sub 'api.${CustomDomain}'
          USER_SERVICE_SECRET_NAME: !Ref UserServiceSecretName
          USER_SERVICE_SECRET_KEY: !Ref UserServiceSecretKey

  TriggerScalableTarget:
    DependsOn:
      - TriggerFunctionAliaslive
      - TriggerFunction
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxConcurrency
      MinCapacity: !Ref MinConcurrency
      ResourceId: !Sub 'function:${TriggerFunction}:live'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency'
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda

  TriggerScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: utilization
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref TriggerScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 0.70
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization

  UserServiceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secret that will be used by users and roles service
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: !Ref UserServiceSecretKey
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Name: !Sub '${ParameterNamePrefix}${UserServiceSecretName}'

  ### Parameters #######################################################################################################

  CognitoAuthenticationDomainPrefixParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${ParameterNamePrefix}CognitoAuthenticationDomainPrefix'
      Description: The prefix for the Cognito domain that hosts the sign-up and sign-in pages for your application.
      Type: String
      Value: !Ref AuthenticationDomainPrefix

  CognitoFrontendApplicationUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${ParameterNamePrefix}CognitoFrontendApplicationUrl'
      Description: A base URL for the callbacks for the identity providers.
      Type: String
      Value: !Ref FrontendApplicationUrl

  FeideMetadataUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${ParameterNamePrefix}FeideMetadataUrl'
      Description: Link to the the identity provider details.
      Type: String
      Value: !Ref FeideMetadataUrl

  CognitoAuthorizerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${ParameterNamePrefix}CognitoAuthorizerArn'
      Description: ARN Identifier of the UserPool
      Type: String
      Value: !GetAtt UserPool.Arn

  CognitoIdentityPoolIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${ParameterNamePrefix}CognitoIdentityPoolId'
      Description: Identifier of the IdentityPool assosiated with the UserPool
      Type: String
      Value: !Ref IdentityPool

  CognitoUserPoolIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Value: !Ref UserPool
      Description: Identifier of the UserPool in Cognito
      Name: !Sub '${ParameterNamePrefix}CognitoUserPoolId'
      Type: String

  CognitoUserPoolAppClientIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${ParameterNamePrefix}CognitoUserPoolAppClientId'
      Description: Identifier to use for the app clients to access this user pool
      Type: String
      Value: !Ref UserPoolClient

  CognitoURNParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${ParameterNamePrefix}CognitoURN'
      Description: URN of the cognito login to use in Feide
      Type: String
      Value: !Sub 'urn:amazon:cognito:sp:${UserPool}'

### Outputs ############################################################################################################

Outputs:
  CognitoDomain:
    Description: Amazon Cognito Domain.
    Value: !Sub 'https://${AuthenticationDomainPrefix}.auth.${AWS::Region}.amazoncognito.com'
  CognitoURN:
    Description: Amazon Cognito URN.
    Value: !Sub 'urn:amazon:cognito:sp:${UserPool}'