plugins {
    id 'nva.identity.service.java-common-conventions'
}

dependencies {
    api(nvaLibs.apigateway)
    api(nvaLibs.core)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.httpcore5)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaLibs.testutils)
}
