openapi: 3.0.1
info:
  title: NVA Roles and Users catalogue
  description: Api for updating users and roles
  version: 1.0.0
paths:
  /roles:
    post:
      summary: Adds new Role
      security:
        - CognitoUserPool: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '200':
          description: Successful creation of role. Returns the generated role
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/Role'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddRoleHandler.Arn}/invocations
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /roles/{role}:
    get:
      summary: Gets an existing Role
      parameters:
        - in: path
          name: role
          schema:
            type: string
          required: true
      security:
        - CognitoUserPool: []
      responses:
        '200':
          description: Successful fetching of role. Returns the requested role
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/Role'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetRoleHandler.Arn}/invocations
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /users:
    post:
      summary: Adds new user
      security:
        - CognitoUserPool: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful creation of role. Returns the generated role
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/User'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddUserHandler.Arn}/invocations
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /users/{username}:
    get:
      summary: Gets an existing User
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
      security:
        - CognitoUserPool: []
      responses:
        '200':
          description: Successful fetching of User. Returns the requested User
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/User'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserHandler.Arn}/invocations
        responses: {}
        httpMethod: POST
        type: aws_proxy
    put:
      summary: Updates an existing User
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      security:
        - CognitoUserPool: []
      responses:
        '202':
          description: Successful request for updating the user. User will be eventually updated
          headers:
            Location:
              schema:
                type: string
              description: Relative path to the user URI
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateUserHandler.Arn}/invocations
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /institutions/users:
    get:
      summary: Lists users of specified institution
      parameters:
        - in: query
          name: institution
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List of users belonging in the specified institue
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      security:
        - CognitoUserPool: []
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListByInstitutionHandler.Arn}/invocations
        responses: {}
        httpMethod: POST
        type: aws_proxy
components:
  schemas:
    AccessRight:
      type: string
      enum:
        - APPROVE_DOI_REQUEST
        - REJECT_DOI_REQUEST
    Role:
      properties:
        type:
          type: string
        rolename:
          type: string
        accessRight:
          type: array
          items:
            $ref: '#/components/schemas/AccessRight'
    User:
      properties:
        type:
          type: string
        username:
          type: string
        givenName:
          type: string
        familyName:
          type: string
        institution:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        accessRight:
          type: array
          items:
            $ref: '#/components/schemas/AccessRight'
  securitySchemes:
    CognitoUserPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - Fn::GetAtt: UserPool.Arn