name: Lint CloudFormation Templates

on: [ push ]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cfn-lint
        uses: scottbrenner/cfn-lint-action@main
        with:
          entrypoint: /bin/sh
          args: "-c \"cat template.yaml | sed '/CODEBUILD_RESOLVED_SOURCE_VERSION/d' | cfn-lint -\""
