name: Lint OpenAPI

on: [ push ]

jobs:
  openapi-linter:

    runs-on: ubuntu-latest

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080

    steps:
      - uses: actions/checkout@v2
      - name: Validate customer OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: docs/customer-swagger.yaml
          
      - uses: actions/checkout@v2
      - name: Validate users&roles OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: docs/users-and-roles-swagger.yaml
